# Generated by Django 4.0.5 on 2022-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Автор'),
        ),
    ]
