# Generated by Django 4.0.5 on 2022-09-13 14:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, populate_from='title', unique=True),
        ),
    ]
